site_name: Research Software Observatory - Data pipeline
site_description: ETL for extraction, transformation, and integration of research software metadata for FAIR assessment.
site_url: https://inab.github.io/research-software-etl/
repo_name: inab/research-software-etl
repo_url: https://github.com/inab/research-software-etl
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  logo: static/OEB-logo.png
  extra_css: 
    - assets/css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets

nav:
  - Overview: index.md
  - Installation & Configuration: installation.md
  - Main Pipeline Stages: pipeline.md
  - CLI Reference: cli.md
  - Development Guide: development.md

plugins:
- search
- mkdocstrings