"""
The command-line interface for the disambiguation step of the integration
"""

import argparse
import logging
import asyncio

from dotenv import load_dotenv

logger = logging.getLogger("rs-etl-pipeline")

async def main():
    parser = argparse.ArgumentParser(
        description="""Resolve conflicts in the grouped entries."""
    )

    parser.add_argument(
        "--blocks-file", "-g",
        help=("Path to the file containing blocks of records. Generated by the grouping and recovery step of the integration. Default is 'data/grouped.json'."),
        type=str,
        dest="blocks_file",
        #default="data/blocks.json",
    )

    parser.add_argument(
        "--conflict-blocks-file", "-d",
        help=("Path to the file containing conflict blocks. This is the output of the 'conflict_detection' process. Default is 'data/disconnected.json'."),
        type=str,
        dest="conflict_blocks_file",
        #default="data/conflict_blocks.json",
    )

    parser.add_argument(
        "--disambiguated-blocks-file", "-n",
        help=("Path to the file where the disambiguated grouped entries and all other groups will be written. Default is 'data/disambiguated_grouped.json'."),
        type=str,
        dest="disambiguated_blocks_file"
    )

    parser.add_argument(
        "--pair_wise_decisions_file", "-p",
        help=(""),
        type=str,
        dest="pair_wise_decisions_file"
    )

    parser.add_argument(
        "--run-id", "-r",
        help=("ID to identify the run. If not set, the datetime of the run will be used. It is added to conflict files."),
        type=str,
        dest="run_id",
        default=None
        )

    parser.add_argument(
        "--env-file", "-e",
        help=("File containing environment variables to be set before running "),
        default=".env",
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Run disambiguation without creating conflict files or GitHub issues. Prints how many issues would be created and the pair IDs involved.",
    )


    args = parser.parse_args()

    # Load the environment variables ------------------------------------------
    logger.debug(f"Env file: {args.env_file}")
    load_dotenv(args.env_file)

    from application.use_cases.integration.disambiguation import run_full_disambiguation
    from infrastructure.config import Credentials, PipelineConfig
    from infrastructure.external.clients import ExternalClients

    # Read the environment once, here, and hand the results down.
    config = PipelineConfig.from_env(
        grouped_json_path=args.blocks_file,
        conflicts_json_path=args.conflict_blocks_file,
        disambiguated_blocks_path=args.disambiguated_blocks_file,
        pair_decisions_path=args.pair_wise_decisions_file,
    )
    credentials = Credentials.from_env().require(
        "github_token", "gitlab_token", "openrouter_api_key", "huggingface_api_key"
    )
    clients = ExternalClients.from_credentials(credentials)

    logger.info(f"Blocks file: {config.grouped_json_path}")
    logger.info(f"Conflict blocks file: {config.conflicts_json_path}")
    logger.info(f"Disambiguated blocks file: {config.disambiguated_blocks_path}")
    logger.info(f"Pair-wise decisions file: {config.pair_decisions_path}")


    logger.info("Disambiguating entries...")
    await run_full_disambiguation(
        blocks_file=config.grouped_json_path,
        conflict_blocks_file=config.conflicts_json_path,
        disambiguated_blocks_file=config.disambiguated_blocks_path,
        pair_wise_decisions_file=config.pair_decisions_path,
        run_id = args.run_id,
        clients=clients,
        dry_run= args.dry_run
    )

    logger.info("Disambiguation finished!")


if __name__ == "__main__":
    print("Running disambiguation...")
    asyncio.run(main())